version: "3"
services:
  db:
    image: mysql:5.7
  backend:
    build:
      context: "./docker/backend"
      dockerfile: "Dockerfile.dev"
    command: python manage.py runserver 0:8000
    volumes:
      - ./src/backend:/code
      - python-packages:/root/.local/share
    ports:
      - "8000:8000"
    links:
      - "db"
volumes:
  python-packages:
